function [value,isterminal,direction] = ground_impact_acrobot(t,in2)
%GROUND_IMPACT_ACROBOT
%    [VALUE,ISTERMINAL,DIRECTION] = GROUND_IMPACT_ACROBOT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    10-Feb-2025 15:13:10

q1 = in2(1,:);
q2 = in2(2,:);
value = sin(q1+q2)+sin(q1);
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = -1.0;
end
end
